<div class="terms">

<p>These Terms of Service (the "Terms") govern your use of the <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, Inc.’s ("<?php echo $app->dependents->SITE_NAME_PROPPER; ?>") website (including all content and functionality available through the www.<?php echo $app->dependents->SITE_NAME; ?>.com domain name, the "Site"), any mobile applications currently provided or to be provided by <?php echo $app->dependents->SITE_NAME_PROPPER; ?> (the “App”), and services provided by <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, Inc. (collectively the “Services”).  Please read these Terms before using or continuing to use the Site and/or App.  The Service is provided to users seeking tutoring services (“Students”) and to users seeking to provide tutoring services (“Tutors”), and to any other entity on whose behalf users accept these Terms.   As used in these Terms, the terms (1) “you”, “your”, and “yours” shall refer to any and all users of the Site and/or App (the “User”) including Students, Tutors or any person or entity who views, uses, accesses, browses or submits any content or material to the Site; and “we”, “us” and “our” shall refer to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>. </p>

<p>By using or continuing to use the Site and/or App, you represent and warrant that you understand, agree to, and accept all terms and conditions contained in these Terms (as may be modified from time to time) and to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>’s Privacy Policy (as may be modified from time to time), which can be found at www.<?php echo $app->dependents->SITE_NAME; ?>.com/privacy-policy (the “Privacy Policy”).  <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may modify these Terms at any time, and such modification shall be effective immediately upon either posting of the modified Terms or notifying you.    You agree to review these Terms periodically to ensure that you are aware of any modifications.   Do not agree to the Terms unless you both fully understand and accept each provision. IF YOU DO NOT AGREE TO THE TERMS AND/OR THE PRIVACY POLICY, YOU DO NOT HAVE <?php echo $app->dependents->SITE_NAME_PROPPER; ?>’S AUTHORIZATION TO USE ANY OF THE SERVICES AND YOU MAY NOT ACCESS OR USE ANY PORTION OF THE SITE OR APP.</p>

<h3>1. General Terms and Limitations.</h3>

<div>
	<ul>
		<li><strong>1.1	General.</strong>
		
		<p>These Terms are entered into by and between <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and you, and you accept them by: (a) contracting for tutoring lessons through the Site or App; (b) using the Site or App in any other manner; and/or (c) acknowledging agreement with these Terms.  To the extent that anything in or associated with the Site and/or App is in conflict or inconsistent with these Terms, the Terms shall control.</p>
		
		</li>

		<li><strong>1.2 Proprietary Rights.</strong>
		
		<p>The entire contents displayed on the Site and App (the “Content”) have copyrighted protection as a collective work under the laws of the United States and other copyright laws.  <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is the sole exclusive owner of the Content.  There may be collective work that is the property of other third parties and such collective work is also protected by copyright and other intellectual property laws.  You are allowed to display and, subject to any expressly stated restrictions or limitations relating to specific material, download portions of the Content from the different areas of the Site only for non-commercial use, unless otherwise permitted.  Any redistribution, retransmission or publication of any copyrighted material is strictly prohibited without the express written permission of the copyright owner.  You may not change or delete any proprietary notices from materials downloaded from the Site or App.  You agree not to use any <?php echo $app->dependents->SITE_NAME_PROPPER; ?> Trademarks (as defined herein) without <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'s express written consent.  "<?php echo $app->dependents->SITE_NAME_PROPPER; ?> Trademarks" means all names, marks, brands, logos, designs, trade dress, slogans and other designations <?php echo $app->dependents->SITE_NAME_PROPPER; ?> uses in connection with its products and Services. You acknowledge <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'s rights in <?php echo $app->dependents->SITE_NAME_PROPPER; ?> Trademarks and agree that any use of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> Trademarks by you shall inure to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'s sole benefit. You agree not to incorporate any <?php echo $app->dependents->SITE_NAME_PROPPER; ?> Trademarks into your trademarks, service marks, company names, internet addresses, domain names, or any other similar designations, for use on or in connection with computer or internet-related products, services or technologies. As between the parties, title, ownership rights, and intellectual property rights in the Content, and any copies or portions thereof, shall remain in <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and/or its content providers.  Third-party trademarks, service marks and logos contained in the Site are owned and licensed by their respective owners.  Any and all rights not expressly granted herein are reserved.</p>
		
		</li>
		
		<li><strong>1.3	Grant of Limited License.</strong>
		
		<p>Your access to the Service is licensed and not sold.  Subject to the Terms and upon your registration for an Account (as defined herein), <?php echo $app->dependents->SITE_NAME_PROPPER; ?> hereby grants you a revocable, non-exclusive, non-transferable account enabling you to access and use the Services, the App and the Site.  All the Content that is made available to view and/or download in connection with the Site and App is owned by and is the copyrighted work of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and/or its suppliers and is licensed, not sold.  You do not have the right to lend, lease, rent or sublicense the Site, the App and/or the Content.  Your use of the Services (including the use of the materials that you download in connection with the use of the App, along with any documentation, text, software, photos, video, graphics, and music, sound or other multimedia files that might accompany it (collectively, “Material”)) is governed by the terms of these Terms.  We reserve the right, without notice and in our sole discretion, to terminate your license to use the Site, App and Services, and to block or prevent future access to and use of the Site, App and Services.  You are not permitted, directly or indirectly, and the foregoing license grant does NOT include the right for You to (a) publish, publicly perform or display, or distribute to any third party any Materials, including reproduction on any computer network or broadcast or publications media; (b) market, sell or make commercial use of the Site, App, or any Material; (c) deep-link to the Site for any purpose or systematically collect and use any data or content including the use of any data spiders, robots, or similar data gathering, mining or extraction methods; (d) make derivative uses of the Site, App, or the Material; or (e) use, frame or utilize framing techniques to enclose any portion of the Site, App (including the images found at this Site, App, or any text or the layout/design of any page or form contained on a page).</p>
		
		</li>
		
		<li><strong>1.4	Use of the App.</strong>
		
			<ol>
				<li><strong>General.</strong> In addition to these Terms, your use of the App is subject to the following additional terms (the “App Terms”): you understand and agree that (i) your use of the App is conditioned upon your acceptance of these App Terms, (ii) the App contains copyrighted material, trade secrets, and other proprietary materials of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and its licensors, and (iii) in order to protect those proprietary materials, except as expressly permitted by applicable law, neither you nor a third party acting on your behalf will: (1) decompile, disassemble or reverse engineer the App; (2) modify or create derivative works of the App; (3) use the App in any manner to provide service bureau, commercial time-sharing or other computer services to third parties; (4) transmit the App or provide its functionality, in whole or in part, over the Internet or other network (except as expressly permitted above); (5) sell, distribute, rent, lease, sublicense or otherwise transfer the App to a third party; or (6) use components of the App to run applications not running on the App. </li>

				<li><strong>App User Agreement.</strong> YOU HEREBY AGREE: (i) to only use the App to access and/or use the Services; (ii) to not use any software or services in conjunction with the Service or authorized third-party software which modifies or reroutes, or attempts to modify or reroute, the Service; (iii) will not authorize any third party to access and/or use the Service on your behalf using any automated process such as a BOT, a spider or periodic caching of information stored by the Service on your behalf without a separate written agreement with <?php echo $app->dependents->SITE_NAME_PROPPER; ?>; (iv) will not use any software or hardware that reduces the number of Users directly accessing or using the Service (sometimes called 'multiplexing' or 'pooling' software or hardware); (v) will not lend, lease, rent or sublicense the App; (vi) to permit <?php echo $app->dependents->SITE_NAME_PROPPER; ?> to send and deliver updates to you as part of your use of the App; and (vii) to allow the App to automatically download and install updates from time to time from <?php echo $app->dependents->SITE_NAME_PROPPER; ?> which are designed to improve, enhance and further develop the App and may take the form of bug fixes, enhanced functions, new software modules and completely new versions.</li>
			</ol>
		
		</li>
	</ul>
</div>

<h3>2. Services.</h3>
	<p>The Site and App offers a marketplace for Users seeking tutoring services to connect with Users seeking to provide tutoring services in a variety of academic subjects. As independent contractors hired by Students, Tutors control the methods, materials and all aspects of the lessons. Students are responsible for selecting the right Tutor for their needs. In making hiring decisions, Students should review and investigate each Tutor's self-reported credentials, education, and experience, as well as reviews from other Students. <strong>You understand that ALL TUTORING SESSIONS SHOULD BE SUPERVISED BY A RESPONSIBLE ADULT.</strong> </p>
	
	<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> controls and operates the Site and App from various locations and makes no representation that the Site or App is appropriate or available for use in all locations. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> services may not be available in your location, and available services may vary among locations. In addition, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> will attempt to deliver all correspondence sent via the Site's messaging system. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not, however, guarantee delivery of all messages.</p>

<h3>3. Academic Honesty.</h3>
<p>You acknowledge and agree that the Services are provided for the purpose of facilitating learning, not cheating. You agree not to inquire about the hiring of or to hire Tutors to complete assignments, write papers, take quizzes or otherwise do work on your behalf. Further, you agree not to use <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'s Services for any purpose that violates the academic honesty policy or other conduct policies of your school, university, academic institution or workplace.</p>

<h3>4. Your Obligations and Conduct.</h3>

	<ul>
		
		<li><strong>4.1	User Agreement. </strong>
		
			<p>In order to access the Service, you will be required to register for an <?php echo $app->dependents->SITE_NAME_PROPPER; ?> account (an “Account”).  If applicable and made available by <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, you may register for an Account by allowing us to access your name and other profile information through existing accounts you may have on sites such as Google or on social networking websites, such as Facebook or Twitter (collectively, “SN Websites”, and each of Your SN Website profile, a “SN Website Profile”). In consideration of your use of the Site, you agree: (a) that you are of legal age and have the power, authority or consent to enter into and perform your obligations under these Terms; (b) to provide accurate, current, and complete information about you as may be prompted by a registration form on the website ("Registration Data") including any credit card information (your “Credit Card”); (c) are authorized, or have the permission of the authorized signatory of the Credit Card or charge card provided to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, to pay any fees incurred from use of the Services; (d) to authorize <?php echo $app->dependents->SITE_NAME_PROPPER; ?> to charge your Credit Card for any and all service fees incurred by your use of Services; (e) to maintain the security of your password and identification; (f) to maintain and promptly update the Registration Data and any information you provide to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, to keep it accurate, current and complete; (g) to accept all risks of unauthorized access to information and Registration Data; (h) to maintain all charges resulting from the use of your Account; (i) to comply with all applicable U.S. and international laws, statutes, ordinances, rules, regulations, contracts and applicable licenses regarding your use of the Services or Site; and (j) that each time you upload Submitted Content (as defined herein) on the Site, App or through the Service, you own or otherwise control the rights or have the necessary consents to upload or post such Submitted Content and to enable inclusion and use of the Submitted Content in the manner contemplated by the Site and/or App.  If you provide any information that is untrue, inaccurate, not current or incomplete, or <?php echo $app->dependents->SITE_NAME_PROPPER; ?> has reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> has the right to suspend or terminate your Account and refuse any and all current or future use of the Services (or any portion thereof). You are not permitted to use the Site, App or Services or provide Submitted Content if you are under the age of 13.</p>
			
		</li>

		<li><strong>4.2	Submitted Content.</strong>
		
			 <p>You are entirely responsible for all content that you upload, post, or otherwise transmit through your use of the Site and/or App (your "Submitted Content"). You agree not to upload, post or otherwise transmit Submitted Content that: (a) is inaccurate, harmful, obscene, pornographic, defamatory, racist, violent, offensive, harassing, or otherwise objectionable to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> or other users of the website; (b) includes unauthorized disclosure of personal information; (c) violates or infringes anyone's intellectual property rights; or (d) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves the right to edit or remove Content that violates these Terms, that contains third-party commercial advertisements, or for any other reason it deems necessary.</p>
			 
			 <p>By posting any Submitted Content on publicly accessible locations on the Site or the App, you automatically grant (or warrant that the owner of such content has expressly granted) to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> a perpetual, royalty-free, non-exclusive, irrevocable, unrestricted, worldwide license to use, copy, sublicense, reproduce, distribute, redistribute, modify, adapt, publish, edit, translate, transmit, create derivative works of, publish and/or broadcast, publicly perform or display any materials or other information (including without limitation, ideas contained therein for new or improved products or services) you submit to public areas of the Site or App, alone or as part of other works in any form, media, or technology whether by any means and in any media now known or hereafter developed and to sublicense such rights through multiple tiers of sublicenses.  Unless otherwise stated herein, any Submitted Content that you provide in connection with the Site and/or App shall be deemed to be provided on a non-confidential basis.  You further acknowledge and agree that your name, likeness, and/or SN Website Profile, as applicable, may be associated with your Submitted Content and you hereby grant us a perpetual, royalty-free, non-exclusive, irrevocable, unrestricted, worldwide license to use Your name, likeness, and/or SN Website Profile, as applicable, in association with your Submitted Content. You agree that you shall have no recourse against <?php echo $app->dependents->SITE_NAME_PROPPER; ?> for any alleged or actual infringement or misappropriation of any proprietary right in your communication to us.  You hereby agree to also grant each User a non-exclusive license to access your Submitted Content through the Site and/or the App, and to use, reproduce, distribute, display and perform such Submitted Content as permitted through the functionality of the Site, the App and under these Terms.   You further acknowledge and agree that no compensation will be paid with respect to the use of your comments, as provided herein, and that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may remove any comment at any time in its sole discretion.  Further, when you post any Submitted Content on the Site and/or the App, you authorize and direct <?php echo $app->dependents->SITE_NAME_PROPPER; ?> to make such copies thereof as <?php echo $app->dependents->SITE_NAME_PROPPER; ?> deems necessary in order to facilitate the posting and storage of such content on the Site.  You may remove any Submitted Content you post from the Site and App at any time. If you choose to remove your Submitted Content, the license granted above will automatically expire; however, you acknowledge that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may retain archived copies of the Submitted Content.</p>
			 
			 <p>You understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves all of its rights under the Communications Decency Act, including without limitation its right to remove anything objectionable to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> in its sole discretion. Alleged improprieties by any User may be reported to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> by email at <span>support@<?php echo $app->dependents->SITE_NAME_PROPPER; ?>.com</span>.</p>
		
		</li>
		
		<li>
		
		<strong>4.3	User Warranties and Representations.</strong>
		<div>You agree to use the Site and/or App in a manner that is lawful, relevant and proper to the applicable forum. Any use of the Site and/or App that <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, in its sole discretion, finds inappropriate and/or offensive may result in suspension and/or termination of a User with or without notice. Conduct that is inappropriate and/or offensive includes without limitation the following:</div>
		
		<ul>
			<li>Defame, abuse, harass, harm, stalk, threaten or otherwise violate the legal rights (including without limitation rights of privacy and publicity) of others;</li>
			<li>Publish, post, upload, distribute or disseminate any profane, defamatory, infringing, hateful, distasteful, obscene or unlawful topic, name, information, materials or content;</li>
			<li>Use the Site, App or Services for any purpose that is in violation of local, state, national, or international law, including without limitation wage/hour and working condition laws and regulations;</li>
			<li>Upload files that contain software or other material that violates the rights of any third party, including without limitation intellectual property rights or rights of privacy or publicity;</li>
			<li>Upload files that contain viruses, Trojan horses, worms, time bombs, spiders, cancel bots, corrupted files, or any other similar software, malware or materials that may damage, interfere with, disrupt, impair, disable or otherwise overburden the operation of any device, computer system or network;</li>
			<li>Take any action that would undermine any aspect of the Site and/or App;</li>
			<li>Attempt to gain unauthorized access to the Site, App, other User accounts, or other device, computer system or networks connected to the Site or App;</li>
			<li>Advertise or offer to sell any goods or services for any commercial purpose on the Site or App that are not appropriate or relevant to the Services;</li>
			<li>Impersonate another person or allow any other person or entity to use your User name, password or membership;</li>
			<li>Post the same content repeatedly or spam - spamming is strictly prohibited;</li>
			<li>Download any file posted by another User that you know, or reasonably should know, cannot be legally distributed through the Site or App;</li>
			<li>Access, download, or copy any information, content and/or materials from the Site or App through artificial means (including without limitation spiders, scrapers, hacking devices, computer programs, bots or other such means);</li>
			<li>Reproduce, duplicate, copy, sell, re-sell or exploit any information, materials or content on the Site or App; or</li>
			<li>Restrict or inhibit any other user from using and enjoying the Site and/or App.</li>
		</ul>
		
		<p>By using the Site, App or Services you further represent and warrant that you currently meet and will continue to meet the following eligibility conditions ("Eligibility Conditions") for as long as you use the Site, App or Services: (a) you have and will at all times comply with all laws and regulations; (b) neither you, nor anyone in your home: (i) has been the subject of a complaint, restraining order or any other legal action involving violence, abuse, neglect, fraud, larceny, or any offense that involves endangering the safety of others; (ii) has been convicted of a crime of any nature, including any felony or misdemeanor of any kind, including without limitation any sexual, child abuse or domestic violence offenses; and/or (iii) has been and/or is currently required to register as a sex offender in any jurisdiction or with any government entity; and (c) neither you, nor anyone in your home, is currently out on bail or on your own recognizance pending trial, relating to any felony or misdemeanor charges of any kind, including without limitation sexual, child abuse or domestic violence offenses.   By using the Site, App or Services, you understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may rely on the Eligibility Conditions, representations and warranties as true. You understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may revise the Eligibility Conditions from time to time and require new conditions and certifications and that User will abide by such revised Eligibility Conditions or discontinue using the Site.</p>
		
		<p>You hereby authorize <?php echo $app->dependents->SITE_NAME_PROPPER; ?> to verify the above representations and warranties by you and you acknowledge and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> shall have the right, but not the obligation, to verify such representations and warranties. You agree and understand that such verification may include, without limitation, conducting criminal background checks, sex offender registry checks, motor vehicle records checks, identification verifications, credit checks and/or use of available public records. You consent to any collection, use or disclosure in order to accomplish such verification. You further agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may take such action as it, in its sole discretion, deems appropriate, including without limitation suspending and/or terminating your use of the Site, App or Services, should it determine that you have violated any representation or warranty.</p>
		
		<p>The preceding paragraph notwithstanding, you understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is not required to and does not conduct background checks of any User. You also understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> neither confirms nor denies the validity of information provided by Users and that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not verify that any or all of the Eligibility Conditions are met by Users.</p> 
		
		<p><strong>You understand and agree to make your own decisions and assessments about persons to engage and that  IT IS YOUR SOLE RESPONSIBILITY TO CONDUCT ANY AND ALL BACKGROUND AND REFERENCE CHECKS REGARDING OTHER USERS.  <?php echo $app->dependents->SITE_NAME_PROPPER; ?> expressly disclaims, and you hereby expressly release <?php echo $app->dependents->SITE_NAME_PROPPER; ?> from, any and all liability whatsoever for any controversies, claims, suits, injuries, damages and/or death arising from and/or in any way related to: (a) any inaccuracy, untimeliness or incompleteness regarding a User's Eligibility Conditions, (b) any acts committed against you by another User, and/or (c) misstatements or misrepresentations made by any User.</strong></p>
		
		</li>
		
	</ul>



<h3>5. Third Party Reports.</h3>
<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> may utilize third party consumer reporting agencies that perform, among other things, criminal background checks, sex offender registry checks, motor vehicle records checks, credit checks, and identification verifications (collectively, the "Consumer Reports"). <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not endorse or make any representations or warranties regarding the reliability of such Consumer Reports or the accuracy, timeliness or completeness of any information in the Consumer Reports. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not independently verify information in the Consumer Reports.</p>

<p>You hereby consent to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> collecting, using and disclosing the information in the Consumer Reports. You understand and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may, in its sole discretion, review and rely on the information in the Consumer Reports in deciding whether to suspend or terminate a User or to investigate a complaint about a User, but that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> shall not be responsible or liable in any way in the event that any information in the Consumer Reports about any person, including without limitation any User, is not accurate, timely or complete. Users who are the subject of Consumer Reports may contact the service provider to dispute the accuracy, timeliness or completeness of such information. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves the right to suspend and/or terminate User based on information in the Consumer Reports or for any other reason in <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'s sole discretion.</p>


<h3>6. Confidentiality of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> Information.</h3>
<p>You may obtain direct access via the Site and/or App to certain confidential information of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and its affiliates, including without limitation technical, contractual, product, program, pricing, marketing and other valuable information that should reasonably be understood as confidential ("Confidential Information"). You must hold Confidential Information in strict confidence. All right, title and interest in the Confidential Information remains with <?php echo $app->dependents->SITE_NAME_PROPPER; ?> and its affiliates.</p>

<p>The Terms impose no obligation upon you with respect to Confidential Information that you can establish by legally sufficient evidence: (a) you possessed prior to your receipt from <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, without an obligation to maintain its confidentiality; (b) is or becomes generally known to the public through no act or omission by you, or otherwise without violation of the Terms; (c) you obtained from a third party who had the right to disclose it, without an obligation to keep such information confidential; (d) you independently developed without the use of Confidential Information and without the participation of individuals who have had access to it, or (e) in response to a valid order by a court or other governmental body, as otherwise required by law, or as necessary to establish the rights of either party under these Terms and as disclosed after prior notice to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> adequate to afford <?php echo $app->dependents->SITE_NAME_PROPPER; ?> the opportunity to object to the disclosure.</p>

<h3>7. Terms of Transacting Business Between Tutors and Students.</h3>

<p>You understand and agree to abide by <?php echo $app->dependents->SITE_NAME_PROPPER; ?>’s Tutor and Student payment policies. You agree that you are willing to pay all costs associated with the Services through <?php echo $app->dependents->SITE_NAME_PROPPER; ?>. These costs include but are not limited to: (a) a Tutor’s hourly rate as listed; (b) travel and transportation fees; (c) cancellation fees as described in a Tutor’s cancellation policy, which can be found on a Tutor’s profile on the Site; and (d) the commission arrangement between the Tutor and <?php echo $app->dependents->SITE_NAME_PROPPER; ?>.  </p>

<h3>8. Third Party Verification Services.</h3>
<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> may make available one or more third party verification services that enable Users of the Site to inquire about information including, but not limited to, another User’s identity and criminal history. Use of a third party verification service is voluntary for both the party requesting the verification and the party undergoing the verification. You agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> shall not be held responsible or liable in any way if any information provided by a third party verification service is inaccurate. When a third party verification service is used, you warrant that you will comply with the Fair Credit Reporting Act, 15 USC 1681. See http://www.consumer.ftc.gov/articles/pdf-0111-fair-credit-reporting-act.pdf for details.</p>

<h3>9. Advertisements and Promotions.</h3>
<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> may run advertisements and promotions from third parties on the Site. Your correspondence or business dealings with, or participation in promotions of, advertisers other than <?php echo $app->dependents->SITE_NAME_PROPPER; ?> found on or through the Site, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such non-<?php echo $app->dependents->SITE_NAME_PROPPER; ?> advertisers on the Site.</p>

<h3>10. Links to Third Party Content.</h3>
<p>You may find links to other websites or resources on the Site. You acknowledge and agree that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any content, advertising, products, or other materials on or available from such sites or resources. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> will not be responsible or liable, directly or indirectly, for any actual or alleged damage or loss caused by or in connection with use of or reliance on any such content, goods or services available on or through any such site or resource.</p>

<h3>11. Termination and Suspension.</h3>
<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves the right to suspend and/or terminate any User with or without notice at any time in its sole discretion, for any reason or no reason. You agree that, if you are suspended and/or terminated, you will make no further use of the Site, App or Services after termination or during suspension.</p>

<h3>12. Disclaimer of Warranties.</h3>
<ul>
	<li><strong>12.1	General Disclaimer.</strong>
		
		<p>USE OF THE SITE IS AT YOUR SOLE RISK UNLESS OTHERWISE EXPLICITLY STATED. THE SITE, INCLUDING THE INFORMATION, SERVICES, AND CONTENT, IS PROVIDED ON AN "AS IS", "AS AVAILABLE", AND "WITH ALL FAULTS" BASIS. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> DISCLAIMS ALL EXPRESS OR IMPLIED CONDITIONS, REPRESENTATIONS, AND WARRANTIES OF ANY KIND, INCLUDING ANY IMPLIED WARRANTY OR CONDITION OF MERCHANTABILITY, SATISFACTORY QUALITY, OR FITNESS FOR A PARTICULAR PURPOSE. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> MAKES NO REPRESENTATIONS, WARRANTIES, CONDITIONS OR GUARANTEES AS TO THE USEFULNESS, QUALITY, SUITABILITY, TRUTH, ACCURACY, OR COMPLETENESS OF THE SITE.</p>
		
		<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> MAKES NO WARRANTY OR REPRESENTATIONS THAT: (A) THE SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; (B) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE WILL BE ACCURATE OR RELIABLE; (C) THE QUALITY OF ANY PRODUCTS, SERVICES, CONTENT, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED FROM TUTORS WILL MEET YOUR EXPECTATIONS OR REQUIREMENTS; OR (D) ANY ERRORS IN THE SITE WILL BE CORRECTED. YOU ASSUME ALL RISK FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM OBTAINING ANY CONTENT FROM THE SITE, INCLUDING ANY DAMAGES RESULTING FROM COMPUTER VIRUSES.</p>
	
	</li>

	<li><strong>12.2	Informational Purposes Only.</strong>
	<p>Any opinions expressed on the Site or the App are the personal opinions of the original author and not of <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, even though the original author may be employed by <?php echo $app->dependents->SITE_NAME_PROPPER; ?>.  The Content is provided for informational purposes only and is not an endorsement or representation by <?php echo $app->dependents->SITE_NAME_PROPPER; ?> or any other party.  <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not assume any responsibility or liability for any Submitted Content, blogs, opinions or other commentary posted on the Site, the App or any third party website linked to the Site or App and makes no express or implied warranty or guarantee about the accuracy, copyright compliance, legality, or any other aspect of the Content.</p>
	</li> 

	<li><strong>12.3	Disclaimer of Third Party Information.</strong>
	<p>You understand that when using the Site and/or the App, you may be exposed to Submitted Content and third party content from a variety of sources, and that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such Submitted Content or third party content.  You further understand and acknowledge that you may be exposed to Submitted Content and third party content that may be offensive, indecent, inaccurate, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against <?php echo $app->dependents->SITE_NAME_PROPPER; ?> with respect thereto.   You acknowledge that statements made in Site, the App, newsgroups, message boards, email, forums, conferences, chats and/or Submitted Content reflect only the views of their authors.  Forum managers, forum hosts, content providers, or merchants appearing on the Site and the App, if applicable, are not authorized <?php echo $app->dependents->SITE_NAME_PROPPER; ?> spokespersons, and their views do not necessarily reflect those of <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, and <?php echo $app->dependents->SITE_NAME_PROPPER; ?> does not endorse any Submitted Content or any opinion, recommendation, or advice expressed therein.</p></li>
</ul>
 

<h3>13. Limitation of Liability.</h3>
<p>THE SITE AND APP OFFERS A MARKETPLACE FOR THOSE SEEKING TUTORING SERVICES TO CONNECT WITH THOSE SEEKING TO PROVIDE TUTORING SERVICES. YOU UNDERSTAND AND AGREE THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> HAS NO CONTROL OVER THE ACTS OR OMISSIONS OF ANY USER AND THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE QUALITY OF THE SERVICES PROVIDED BY ANY USER. YOU UNDERSTAND AND AGREE THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> IS NOT RESPONSIBLE FOR THE PERFORMANCE OR CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE SITE AND APP. AS SUCH, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> EXPRESSLY DISCLAIMS ANY AND ALL LIABILITY WHATSOEVER FOR ANY CONTROVERSIES, CLAIMS, SUITS, INJURIES AND/OR DAMAGES ARISING FROM AND/OR IN ANY WAY RELATED TO THE SITE, APP AND SERVICES.</p>

USERS OF THE SITE, APP AND SERVICES TRANSACT BETWEEN THEMSELVES. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> WILL NOT BE INVOLVED IN ANY USER INTERACTIONS. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> IS NOT RESPONSIBLE FOR DISPUTES, CLAIMS, LOSS, INJURY, DAMAGE OR DEATH OF ANY KIND THAT MIGHT ARISE DURING AND AFTER USER INTERACTION. Any disputes related to Tutor charges, Student payments and/or refunds are governed by each Tutor’s respective policy as posted on a Tutor’s profile.  Students and Tutors understand and agree that any such disputes will be handled between the two parties and that <?php echo $app->dependents->SITE_NAME_PROPPER; ?> is not responsible for refunding any fees and/or obligated to resolve any payment issues between Tutors and Students.

<p>YOU UNDERSTAND AND AGREE THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> HAS NO CONTROL OVER THE ACTS OR OMISSIONS OF ANY USER ON OR OFF THE SITE AND APP AND THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE QUALITY OF THE SERVICES PROVIDED BY ANY USER. YOU UNDERSTAND AND AGREE THAT <?php echo $app->dependents->SITE_NAME_PROPPER; ?> IS NOT RESPONSIBLE FOR THE PERFORMANCE OR CONDUCT, WHETHER ON OR OFF THE SITE AND APP, OF ANY USER. AS SUCH, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> EXPRESSLY DISCLAIMS, AND EACH USER EXPRESSLY RELEASES <?php echo $app->dependents->SITE_NAME_PROPPER; ?> FROM, ANY AND ALL LIABILITY WHATSOEVER FOR ANY CONTROVERSIES, CLAIMS, SUITS, INJURIES AND/OR DAMAGES ARISING FROM AND/OR IN ANY WAY RELATED TO THE SITE, INCLUDING WITHOUT LIMITATION ANY ACTS AND/OR OMISSIONS OF USERS ON OR OFF THE SITE AND APP.</p>

<p>TO THE FULL EXTENT PERMITTED BY LAW, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> IS NOT LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING WITHOUT LIMITATION LOSS OF BUSINESS, REVENUE, PROFITS, GOODWILL, USE, DATA, ELECTRONICALLY TRANSMITTED ORDERS, OR OTHER ECONOMIC ADVANTAGE) ARISING OUT OF OR IN CONNECTION WITH THE SITE, APP AND SERVICES, EVEN IF <?php echo $app->dependents->SITE_NAME_PROPPER; ?> HAS PREVIOUSLY BEEN ADVISED OF, OR REASONABLY COULD HAVE FORESEEN, THE POSSIBILITY OF SUCH DAMAGES, HOWEVER THEY ARISE, WHETHER IN BREACH OF CONTRACT OR IN TORT (INCLUDING NEGLIGENCE), INCLUDING WITHOUT LIMITATION DAMAGES DUE TO: (A) THE USE OF OR THE INABILITY TO USE THE SITE, APP OR SERVICES; (B) THE COST OR PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION, OR SERVICES PURCHASED OR OBTAINED, OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO, THROUGH OR FROM THE SITE OR APP; (C) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SITE OR APP, INCLUDING WITHOUT LIMITATION UNAUTHORIZED ACCESS TO OR ALTERATION OF TRANSMISSION OR DATA, MALICIOUS OR CRIMINAL BEHAVIOR, OR FALSE OR FRAUDULENT TRANSACTIONS; OR (D) CONTENT OR INFORMATION USERS MAY DOWNLOAD, USE, MODIFY, OR DISTRIBUTE. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. IN NO EVENT SHALL <?php echo $app->dependents->SITE_NAME_PROPPER; ?>'S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING BUT NOT LIMITED TO, NEGLIGENCE) OR OTHERWISE, EXCEED (A) THE AMOUNT PAID BY YOU TO <?php echo $app->dependents->SITE_NAME_PROPPER; ?> OR AN <?php echo $app->dependents->SITE_NAME_PROPPER; ?> PARTNER, IF ANY, OR (B) $100 (WHICHEVER IS LESS).</p>

<p>YOU AND <?php echo $app->dependents->SITE_NAME_PROPPER; ?> AGREE THAT THE WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY IN THESE TERMS OF SERVICE ARE MATERIAL, BARGAINED-FOR BASES OF THESE TERMS, AND THAT THEY HAVE BEEN TAKEN INTO ACCOUNT IN DETERMINING THE CONSIDERATION TO BE GIVEN BY EACH PARTY UNDER THESE TERMS AND IN THE DECISION BY EACH PARTY TO ENTER INTO THESE TERMS. YOU AND <?php echo $app->dependents->SITE_NAME_PROPPER; ?> AGREE THAT THE WARRANTY DISCLAIMERS AND LIMITATIONS OF LIABILITY IN THESE TERMS OF SERVICE ARE FAIR AND REASONABLE.</p>

<p>IF YOU ARE DISSATISFIED WITH THE SITE, APP OR SERVICE OR DO NOT AGREE TO ANY PROVISIONS OF THESE TERMS, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE, APP AND SERVICES, EXCEPT AS MAY BE PROVIDED FOR IN THIS SECTION 13.</p>

<h3>14. Assumption of Risk.</h3>
<p>You agree and understand that you assume all risks when using the Site, App and Services, including without limitation any and all of the risks associated with any online or offline interactions with other Users. You agree to take all necessary precautions, including without limitation following the recommendations set forth in <?php echo $app->dependents->SITE_NAME_PROPPER; ?>’s Tutor and Student Safety Tips, when interacting with other Users.</p>

<h3>15. Indemnification and Arbitration.</h3>
<p>YOU AGREE TO INDEMNIFY, DEFEND AND HOLD HARMLESS <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, INFORMATION PROVIDERS, SUBSIDIARIES, AFFILIATES AND SUPPLIERS FROM AND AGAINST ALL LOSSES, EXPENSES, DAMAGES AND COSTS, INCLUDING REASONABLE ATTORNEY'S FEES, RESULTING FROM ANY VIOLATION OF THeSE TERMS, BREACH OF YOUR REPRESENTATIONS and warranties CONTAINED HEREIN, disputes with or between other Users, inaccurate, untimely, incomplete or misleading User information, including without limitation with respect to Registration Date, profile or Eligibility Conditions, OR ANY ACTIVITY RELATED TO YOUR ACCOUNT (INCLUDING INFRINGEMENT OF THIRD PARTIES' WORLDWIDE INTELLECTUAL PROPERTY RIGHTS OR NEGLIGENT OR WRONGFUL CONDUCT) BY YOU OR ANY OTHER PERSON ACCESSING THE SITE OR THE APP USING YOUR ACCOUNT.  You agree that you will cooperate as requested by <?php echo $app->dependents->SITE_NAME_PROPPER; ?> in the defense of such claims. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by Users, and you shall not, in any event, settle any claim or matter on behalf of <?php echo $app->dependents->SITE_NAME_PROPPER; ?> without the written consent of <?php echo $app->dependents->SITE_NAME_PROPPER; ?>.</p>

<p>Any controversy, claim, suit, injury or damage arising from or in any way related to the App, the Site, its use, a Tutor or Student’s conduct, or the Terms shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association then in effect and before a single arbitrator chosen by <?php echo $app->dependents->SITE_NAME_PROPPER; ?>. Any such controversy, claim, suit, injury or damage shall be arbitrated on an individual basis, and shall not be consolidated in any arbitration with any controversy, claim, suit, injury or damage of any other party. The arbitration shall be conducted in Scottsdale, Arizona, and judgment of the arbitration award may be entered into any court having jurisdiction thereof. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may seek any interim or preliminary relief from a court of competent jurisdiction in Scottsdale, Arizona, necessary to protect its rights pending the completion of arbitration. Each party shall assume its own costs of arbitration.</p>

<h3>16. Injunction.</h3>
<p>You agree that any material breach of the Terms will result in irreparable harm to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> for which damages would be an inadequate remedy and, therefore, in addition to its rights and remedies otherwise available at law, <?php echo $app->dependents->SITE_NAME_PROPPER; ?> will be entitled to equitable relief, including both a preliminary and permanent injunction, if such a breach occurs. You waive any requirement for the posting of a bond or other security if <?php echo $app->dependents->SITE_NAME_PROPPER; ?> seeks such an injunction.</p>

<h3>17. Notices; Modification and Termination of Services.</h3>
<p><?php echo $app->dependents->SITE_NAME_PROPPER; ?> may provide notice to Users via email, regular mail, or by posting notices or links to notices on the Site. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> reserves the right at any time to modify, suspend or terminate the Services (or any part thereof), and/or use of or access to them, with or without notice. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may also delete, or bar access to or use of, all related information and files. <?php echo $app->dependents->SITE_NAME_PROPPER; ?> will not be liable to Users or any third-party for any modification, suspension, or termination of service, or loss of related information.  You may give notice to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> at any time via electronic mail to the Site at the following address:  ATTN: Member Services, <span>support@<?php echo $app->dependents->SITE_NAME_PROPPER; ?>.com</span>. </p>

<h3>18.	Copyright or Intellectual Property Infringement Notification.</h3>
<div><?php echo $app->dependents->SITE_NAME_PROPPER; ?> respects the intellectual property rights of others. You can notify <?php echo $app->dependents->SITE_NAME_PROPPER; ?> of possible copyright infringement, and <?php echo $app->dependents->SITE_NAME_PROPPER; ?> will review all claims of copyright infringement received and remove content deemed to have been posted or distributed in violation of any such laws. To make a claim, please provide the following:</div>

<ul>
	<li>(a)  	A physical or an electronic signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest that is allegedly infringed; </li>
	<li>(b)  	A description of the copyrighted work or other intellectual property that You claim has been infringed; </li>
	<li>(c)  	A description of where the material that You claim is infringing is located on the Site reasonably sufficient to permit <?php echo $app->dependents->SITE_NAME_PROPPER; ?> to locate the material; </li>
	<li>(d)  	Your contact information, including Your address, telephone number, and email; </li>
	<li>(e)  	A statement by You that You have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </li>
	<li>(f)  	A statement by You that the above information in Your notice is accurate and that You, made under penalty of perjury, are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner's behalf. </li>
</ul>

<p>Contact the agent designated to receive and act on copyright violations under the Digital Millennium Copyright Act ("DMCA"). Claims can be directed to us at 1-800-485-3138 <span>support@<?php echo $app->dependents->SITE_NAME_PROPPER; ?>.com</span> or to <?php echo $app->dependents->SITE_NAME_PROPPER; ?>, Inc., 7272 E. Indian School Rd, Suite 540, Scottsdale, Arizona 85251. </p>

<h3>19. Export Controls.</h3>
<p>You shall comply with all export laws and restrictions and regulations of the Department of Commerce, the United States Department of Treasury Office of Foreign Assets Control (“OFAC”), or other United States or foreign agency or authority, and not to export, or allow the export or re-export of the Material in violation of any such restrictions, laws or regulations. By downloading or using the Material, You are agreeing to the foregoing and You are representing and warranting that You are not located in, under the control of, or a national or resident of any restricted country or on any such list. </p>

<h3>20. Miscellaneous.</h3>
<p>These Terms shall be governed by and construed in accordance with the substantive laws, without regard to choice of law rules, of the State of Arizona. These Terms and the Privacy Policy constitute the entire agreement between you and <?php echo $app->dependents->SITE_NAME_PROPPER; ?> relating to their subject matter, and cancel and supersede any prior versions of the Terms and/or Privacy Policy. You may not assign or otherwise transfer the Terms or any right granted hereunder. You also may be subject to additional terms and conditions that may apply when you use <?php echo $app->dependents->SITE_NAME_PROPPER; ?> or third-party products or services. Any cause of action or claim you may have with respect to <?php echo $app->dependents->SITE_NAME_PROPPER; ?> must be commenced within one (1) year after the claim or cause of action arises. <?php echo $app->dependents->SITE_NAME_PROPPER; ?>’s failure to insist upon or enforce strict performance of any provision of these Terms shall not be construed as a waiver of any provision or right. No waiver of any term, provision or condition of these Terms, whether by conduct or otherwise, in any one or more instances, shall be deemed to be, or shall constitute, a waiver of any other term, provision or condition hereof, whether or not similar, nor shall such waiver constitute a continuing waiver of any such term, provision or condition hereof. No waiver shall be binding unless executed in writing by the party making the waiver.  If any action in law or in equity is necessary to enforce these Terms, the prevailing party will be entitled to reasonable fees of attorneys, accountants, and other professionals, and costs and expenses in addition to any other relief to which such prevailing party may be entitled. The provisions of these Terms are severable, and in the event any provision hereof is determined to be invalid or unenforceable, such invalidity or unenforceability shall not in any way affect the validity or enforceability of the remaining provisions hereof.  <?php echo $app->dependents->SITE_NAME_PROPPER; ?> may assign its rights and duties under these Terms to any party at any time without notice to you.</p>


<div><small>Last Updated on May 28, 2015</small></div>

</div>