<h2>This Privacy Policy is effective as of 5/29/2015. </h2>
	
	<p><?php echo SITENAME_PROPPER; ?>, Inc. ("<?php echo SITENAME_PROPPER; ?>") is committed to protecting your privacy and we encourage you to read and learn more about the terms of our privacy policy (the “Privacy Policy”) which covers how we collect, use, communicate and disclose and make use of personal information. By visiting <?php echo SITENAME_PROPPER; ?>’s online website (collectively, including all content and functionality available through the www.<?php echo SITENAME_PROPPER; ?>.com domain name, the "Site") or any mobile applications currently provided or to be provided by <?php echo SITENAME_PROPPER; ?> (the “App”), submitting information or using any of our services (the “Service”), you acknowledge that you accept the practices and policies outlined in this Privacy Policy.  Terms not defined herein shall have the meaning as provided in <?php echo SITENAME_PROPPER; ?>’s Terms of Service, found at www.<?php echo SITENAME_PROPPER; ?>.com/terms-of-service, and incorporated herein.</p>
	
	<p>WE MAY MODIFY THIS PRIVACY POLICY AT ANY TIME, IN OUR SOLE DISCRETION, AND SUCH MODIFICATION SHALL BE EFFECTIVE IMMEDIATELY UPON EITHER POSTING OF THE MODIFIED PRIVACY POLICY ON THE SITE, ON THE APP, OR NOTIFYING YOU.  Use of information we collect now is subject to the Privacy Policy in effect at the time such information is collected.  YOU AGREE TO REVIEW THIS PRIVACY POLICY PERIODICALLY TO ENSURE THAT YOU ARE AWARE OF ANY MODIFICATIONS. YOUR CONTINUED ACCESS OR USE OF THE SITE AND/OR THE APP SHALL BE DEEMED YOUR CONCLUSIVE ACCEPTANCE OF THE MODIFIED PRIVACY POLICY.</p>
	
	<h3>General.</h3>
	<div>The following outlines our Privacy Policy.</div>
	<ul>
		<li>Before or at the time of collecting Personal Information (as defined herein), we will identify the purposes for which information is being collected. </li>
		<li>We will collect and use Personal Information solely with the objective of fulfilling those purposes specified by us and for other compatible purposes, unless we obtain the consent of the individual concerned or as required by law. </li>
		<li>We will only retain Personal Information as long as necessary for the fulfillment of those purposes. </li>
		<li>We will collect Personal Information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned. </li>
		<li>Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date. </li>
		<li>We will protect Personal Information by reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification. </li>
		<li>We will make readily available to customers information about our policies and practices relating to the management of personal information. </li>
	</ul>
	
	
	<p>We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of Personal Information is protected and maintained. </p>
	
	<h3>What is Covered in this Privacy Policy?</h3>
	<p>This Privacy Policy covers <?php echo SITENAME_PROPPER; ?>'s treatment of Personal Information that <?php echo SITENAME_PROPPER; ?> gathers when you are accessing the Site and/or App and when you use any part of the Service.  This Privacy Policy also covers <?php echo SITENAME_PROPPER; ?>'s treatment of any Personal Information that <?php echo SITENAME_PROPPER; ?>'s business partners share with <?php echo SITENAME_PROPPER; ?>.  This Privacy Policy does not apply to the practices of companies that <?php echo SITENAME_PROPPER; ?> does not own or control, or to individuals that <?php echo SITENAME_PROPPER; ?> does not employ or manage.</p>
	
	<h3>Your Personal Information.  </h3>
	
	<ul>
		
		<li><strong>(a)		Collection of Your Personal Information.</strong>
		<p>In order to access the Service, you will be required to register for an <?php echo SITENAME_PROPPER; ?> account (an “Account”).  You may register for an Account by (1) providing certain personally identifiable information (“Personal Information”) such as, and as applicable, your name, e-mail address, mailing address, direct deposit information, professional  experience, telephone number, and/or credit card information, or (2) if applicable, by allowing us to access Your name and other profile information through existing accounts you may have on sites such as Google or on social networking websites, such as Facebook or Twitter (collectively, “SN Websites”, and each of Your SN Website profiles, a “SN Website Profile”).  It is your responsibility to give us current, complete, truthful and accurate information, including Personal Information, and to keep such information up to date.  <?php echo SITENAME_PROPPER; ?> will not be responsible for any problems or liability related to inaccurate or incomplete Personal Information, whether due to your failure to update such Personal Information or otherwise.  If made available by <?php echo SITENAME_PROPPER; ?>, if you register for an Account through the use of a SN Website Profile, you will not be required to directly provide us with any Personal Information as we use the information you have already provided to the SN Website in registering for an account with such SN Website and which you have allowed the SN Website to share with <?php echo SITENAME_PROPPER; ?>, including, but not limited to, your first name, your SN Website user profile picture, your friend's list, pages you are a fan of, your gender, and the networks to which you belong (collectively, your “Submitted Information”).  In addition to the Personal Information and Submitted Information, we may collect the following information You provide (collectively with Personal Information and Submitted Information, the “Information”):</p>
		
		<ul>
				<li>Information associated with messages and invitations that you provided to people in your network through the Services.</li>
				<li>Information from publicly accessible sources, such as blogs and comments from other Users.</li>
				<li>Your visit to the Site, such as pages viewed, links clicked and other similar navigation action in connection with the Site.</li>
				<li>Certain standard browser information, such as your browser type, IP address, and access times.</li>
		</ul>
		
		<p>In using and/or accessing the Services, you expressly authorize us to collect and use your Information in connection with the Services.  You further acknowledge and agree that <?php echo SITENAME_PROPPER; ?> may, but is not obligated to, maintain copies of your Information indefinitely, or delete any or all Information, at our sole discretion.  When you receive promotional e-mails or newsletters from <?php echo SITENAME_PROPPER; ?>, if any, we may use customized links or similar technologies to determine whether such newsletters or e-mail have been opened and which links You click.  This information is used to provide you more focused e-mail communications and/or other information.</p>

		
		</li>
			
		<li>
		<strong>(b)	Use of Your Personal Information.</strong>
		<p><?php echo SITENAME_PROPPER; ?> collects and uses your Information to operate and improve the Site and the App and better deliver the Services. These uses may include performing analysis aimed at improving the Service; making the Site, the App or Services more user friendly by reducing the need for you to repeatedly enter the same information; and displaying advertising and content that are tailored to Your preferences and interests.  If available and you registered for an Account through Your SN Website Profile, <?php echo SITENAME_PROPPER; ?> will not knowingly use, display, or share any of your Information in a manner inconsistent with the privacy settings and policies of the SN Website (collectively, the “SN Policies”) which you registered through (including, for Facebook accounts, Facebook’s Statement of Rights and Responsibilities, currently accessible at https://www.facebook.com/legal/terms).   We advise you to carefully read the terms of use and SN Policies that you access the Services through.  It is your responsibility to read and accept the respective SN Policies prior to accessing and using the Services.</p>
	
	<p><?php echo SITENAME_PROPPER; ?> may support the Site, the App and the Service by advertising, and accordingly, <?php echo SITENAME_PROPPER; ?> may use some of the information collected in order to customize the advertisements to your interests and preferences.  However, the process of selecting customized ads tailored to you will use data that does not personally identify you, such as using demographic data such as ZIP code.  <?php echo SITENAME_PROPPER; ?> may also use your Information to communicate with you, such as providing you with mandatory notices or discretionary notices about the Service.  From time to time, <?php echo SITENAME_PROPPER; ?> may also send you surveys or promotional mailings to inform you of other products or services available from <?php echo SITENAME_PROPPER; ?> and its affiliates.    <?php echo SITENAME_PROPPER; ?> is headquartered in the United States of America.  Information may be accessed by us or transferred to us in the United States or to our affiliates, business partners, or service providers elsewhere in the world. By providing us with Information, you consent to this transfer.  We will protect the privacy and security of Information according to our Privacy Policy, regardless of where it is processed or stored.</p>
		</li>
			
		<li>
		
		<strong>(c)	Disclosing of Your Personal Information to Third Parties.</strong>
		<p><?php echo SITENAME_PROPPER; ?> does not sell, rent, lease or disclose your Personal Information.  Except as described in this Privacy Policy, your Personal Information will be used only by <?php echo SITENAME_PROPPER; ?> and its controlled subsidiaries and affiliates, and your Personal Information will not be disclosed to any other third party without your consent.  By accessing your Account, you may choose to share your Personal Information with select <?php echo SITENAME_PROPPER; ?> partners so that they can contact you about their respective products, services or offers. </p>
	
	<p><?php echo SITENAME_PROPPER; ?> may hire other companies to provide limited administrative and communication services on <?php echo SITENAME_PROPPER; ?>’s behalf, such as hosting sites, the processing and delivery of mailings, providing customer support, processing of and providing Consumer Reports or providing credit card processing services. <?php echo SITENAME_PROPPER; ?> has the right to disclose your Personal Information to these third party companies for the purpose of administering and maintaining the Site and App’s features, functions and operations and in providing the Services.  Those companies will be permitted to obtain only such Personal Information as necessary for them to deliver the respective services, and <?php echo SITENAME_PROPPER; ?> does not authorize these companies to use your Personal Information except for the sole purpose of providing those services requested by <?php echo SITENAME_PROPPER; ?>. </p>
	
	<p>You understand and agree that <?php echo SITENAME_PROPPER; ?> may access and/or disclose Personal Information about you or your Account without your prior consent if <?php echo SITENAME_PROPPER; ?> has a good faith belief that such action is necessary to: (i) comply with legal process or other legal requirements of any governmental authority; (ii) protect and defend the rights or property of <?php echo SITENAME_PROPPER; ?> (including the enforcement of our agreements); (iii) enforce the Terms of Service, which can be accessed at www.<?php echo SITENAME_PROPPER; ?>.com/terms-of-service; (v) operate or conduct maintenance and repair of the Site, the App or equipment as authorized by law; (vi) act in urgent circumstances to protect the personal safety of users of <?php echo SITENAME_PROPPER; ?> Site, the App or members of the public; or (v) comply with a bankruptcy, merger, acquisition, transfer of control, joint venture or other business combination.  <?php echo SITENAME_PROPPER; ?> is not required to question or contest the validity of any search warrant, subpoena or other similar governmental request that we receive.  In some cases, we may choose to buy or sell assets.  In these types of transactions, User information is typically one of the business assets that is transferred.  Moreover, if <?php echo SITENAME_PROPPER; ?>, or substantially all of its assets, were acquired, User information would be one of the assets that is transferred or acquired by a third party.  You acknowledge that such transfers may occur, and that any acquirer of <?php echo SITENAME_PROPPER; ?> may continue to use your Information as set forth in this Privacy Policy.</p>
		
		</li>
	
	<li><strong>(d)	Security of Your Personal Information.</strong>  <p>The Personal Information <?php echo SITENAME_PROPPER; ?> collects is securely stored within our database, and we use standard, industry-wide practices such as firewalls, encryption, and (in certain areas) Secure Socket Layers (“SSL”) for protecting your information. However, as effective as encryption technology is, no security system is impenetrable. <?php echo SITENAME_PROPPER; ?> cannot guarantee the security of our database, nor can we guarantee that information you supply won't be intercepted while being transmitted to <?php echo SITENAME_PROPPER; ?> over the Internet. <?php echo SITENAME_PROPPER; ?> recommends that you not disclose your password to anyone.</p> </li> 
	
	<li><strong>(e)	Collection and Use of Children's Personal Information.</strong>   <p>The Site, the App and the Services are intended for general audiences, and <?php echo SITENAME_PROPPER; ?> does not knowingly collect any Personal Information from children.</p></li>
		
	</ul>  
	
	<h3>Information Collected Automatically.</h3>
	<p>We may from time to time receive and store certain types of information whenever you interact with the Site, the App and/or Service.  <?php echo SITENAME_PROPPER; ?> may choose to automatically receive and record information on our server logs from your browser including your IP address, cookie information, and the page you requested. <?php echo SITENAME_PROPPER; ?> uses "cookies" to collect non-personal data and information. Cookies are small text files a Site uses to recognize repeat users, and is typically placed on your hard disk by a web page server. Cookies contain information that can later be read by a web server in the domain that issued the cookie to you.   The way cookies function is by assigning a number to the user that has no meaning outside of the assigning Site.  You should be aware that <?php echo SITENAME_PROPPER; ?> cannot control the use of cookies (or the resulting information) by <?php echo SITENAME_PROPPER; ?>'s third-party partners or advertisers.  You have the ability to accept or decline cookies.  Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer.  If you choose to decline cookies, you may not be able to sign in or use other interactive features of the Site and Service that depend on cookies.</p>
	
	<p>In addition, <?php echo SITENAME_PROPPER; ?> may from time to time use third party analytics providers and products to obtain, compile and analyze Information about how Users are using and interacting with <?php echo SITENAME_PROPPER; ?> and/or the Services.  <?php echo SITENAME_PROPPER; ?> may provide Information to these analytics providers for the purpose of obtaining statistics and other information about how Users are using and interacting with <?php echo SITENAME_PROPPER; ?>.  These analytics providers may use a variety of established or new tracking technologies or tools (including, without limitation, cookies, web beacons, HTTP cache, local shared objects and persistent identifiers) to recognize your computer or device and/or to collect or compile this information.  <?php echo SITENAME_PROPPER; ?> has no control over the technologies, tools or practices of the third parties that providing analytics products and services to <?php echo SITENAME_PROPPER; ?>.  </p>
	
	<h3>E-mail Communications.</h3>
	<p>Upon registration for an Account or using the Services provided by <?php echo SITENAME_PROPPER; ?>, we may send you daily or weekly e-mails.  If you do not want to receive e-mail or other mail from us, please notify us by e-mail at support@<?php echo SITENAME_PROPPER; ?>.com and include sufficient information for us to identify your account, including your name, email address and the specifics of your request. However, after you unsubscribe to cease receiving e-mails, <?php echo SITENAME_PROPPER; ?> may still contact you via e-mail for administrative or informational purposes, including messages regarding the administration of your Account and/or any services or events to which you have registered.</p>
	
	<h3>Advertisements Displayed by Third Parties.</h3>
	<p><?php echo SITENAME_PROPPER; ?> may allow third-party ad serving companies, including ad networks, to display advertisements on the Site.  Ad serving companies may place a persistent cookie on your computer in order to recognize your computer each time they display an online advertisement to you, and as such, they may be able to compile information over time about whether you reviewed or clicked on advertisements they display.  These companies may use this information to display targeted advertisements and may associate this information with your subsequent visits, purchases or other activities on participating advertisers’ Sites.  <?php echo SITENAME_PROPPER; ?> has no access to or control over cookies of these links to other Sites and organizations, nor does <?php echo SITENAME_PROPPER; ?> have control over or access to cookies by <?php echo SITENAME_PROPPER; ?>’s third-party partners or advertisers.  This Privacy Policy does not cover any use of Personal Information that a third-party advertiser or ad server may collect from you.</p>
	
	<p>Questions or Comments Regarding this Privacy Policy.  <?php echo SITENAME_PROPPER; ?> welcomes any questions or comments you may have regarding this Privacy Policy or if you do not understand any information about how we collect, maintain, use, or share your Personal Information.  Any such questions or comments should be submitted via email to support@<?php echo SITENAME_PROPPER; ?>.com. We will make every effort to resolve or answer your concern. </p>